#!/usr/bin/env python3
"""
Update Supabase rows to point at private S3 objects.

Reads the manifest generated by `scripts/upload_glbs_to_s3.py` and updates a
target table/column.

Recommended default (no DB migration):
  - store `s3://bucket/key` into the existing `glb_url` column
  - update the app API to detect `s3://` and generate a signed GET URL on demand

Usage:
  python scripts/update_supabase_glb_sources.py ^
    --manifest s3_manifest.csv ^
    --supabase-url https://xxxx.supabase.co ^
    --service-role-key YOUR_SERVICE_ROLE_KEY ^
    --table preloaded_models ^
    --id-column id ^
    --target-column glb_url ^
    --dry-run

Then remove --dry-run to actually update.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import requests


@dataclass(frozen=True)
class ManifestRow:
    local_path: str
    product: str
    color: str
    filename: str
    bucket: str
    s3_key: str
    s3_uri: str
    status: str


def _parse_id_from_filename(filename: str) -> Optional[str]:
    # "<id>-<group>.glb"
    m = re.match(r"^(\d+)-", (filename or "").strip())
    return m.group(1) if m else None


def _read_manifest(path: Path) -> list[ManifestRow]:
    rows: list[ManifestRow] = []
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for r in reader:
            if not r:
                continue
            status = (r.get("status") or "").strip()
            # Only apply for successful uploads, or skip if already existed.
            if not (status == "ok" or status.startswith("skip:")):
                continue
            rows.append(
                ManifestRow(
                    local_path=(r.get("local_path") or "").strip(),
                    product=(r.get("product") or "").strip(),
                    color=(r.get("color") or "").strip(),
                    filename=(r.get("filename") or "").strip(),
                    bucket=(r.get("bucket") or "").strip(),
                    s3_key=(r.get("s3_key") or "").strip(),
                    s3_uri=(r.get("s3_uri") or "").strip(),
                    status=status,
                )
            )
    return rows


def _supabase_rest_base(url: str) -> str:
    return url.rstrip("/") + "/rest/v1"


def _patch_row(
    *,
    supabase_url: str,
    service_role_key: str,
    table: str,
    id_column: str,
    row_id: str,
    target_column: str,
    target_value: str,
    dry_run: bool,
) -> tuple[bool, str]:
    endpoint = f"{_supabase_rest_base(supabase_url)}/{table}"
    headers = {
        "apikey": service_role_key,
        "Authorization": f"Bearer {service_role_key}",
        "Content-Type": "application/json",
        "Prefer": "return=minimal",
    }
    params = {id_column: f"eq.{row_id}"}
    payload = {target_column: target_value}

    if dry_run:
        return True, "dry-run"

    try:
        res = requests.patch(endpoint, headers=headers, params=params, json=payload, timeout=30)
    except Exception as e:
        return False, f"request error: {type(e).__name__}: {e}"

    if res.status_code not in (200, 204):
        txt = (res.text or "").strip()
        return False, f"http {res.status_code}: {txt[:200]}"

    return True, "ok"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--manifest", default="s3_manifest.csv", help="Manifest CSV path (default: s3_manifest.csv)")
    p.add_argument("--supabase-url", required=True, help="Supabase project URL")
    p.add_argument("--service-role-key", required=True, help="Supabase service role key")
    p.add_argument("--table", default="preloaded_models", help="Target table (default: preloaded_models)")
    p.add_argument("--id-column", default="id", help="Row id column (default: id)")
    p.add_argument("--target-column", default="glb_url", help="Column to store S3 reference (default: glb_url)")
    p.add_argument("--store", choices=["s3_uri", "s3_key"], default="s3_uri", help="Store s3://.. or key only")
    p.add_argument("--dry-run", action="store_true", help="Do not write to Supabase")
    args = p.parse_args()

    manifest_path = Path(args.manifest).resolve()
    if not manifest_path.exists():
        print(f"Manifest not found: {manifest_path}", file=sys.stderr)
        return 2

    rows = _read_manifest(manifest_path)
    if not rows:
        print("No successful rows in manifest. Nothing to update.")
        return 0

    total = 0
    ok = 0
    failed = 0
    skipped = 0

    for r in rows:
        row_id = _parse_id_from_filename(r.filename)
        if not row_id:
            skipped += 1
            continue

        value = r.s3_uri if args.store == "s3_uri" else r.s3_key

        total += 1
        success, msg = _patch_row(
            supabase_url=args.supabase_url,
            service_role_key=args.service_role_key,
            table=args.table,
            id_column=args.id_column,
            row_id=row_id,
            target_column=args.target_column,
            target_value=value,
            dry_run=bool(args.dry_run),
        )
        if success:
            ok += 1
        else:
            failed += 1
        print(f"[id={row_id} {r.product}/{r.color}/{r.filename}] {msg}")

    print(
        f"\nDone. Considered: {len(rows)} manifest rows. Updated: {ok}/{total}. "
        f"Skipped (no id): {skipped}. Failed: {failed}. Dry-run: {bool(args.dry_run)}"
    )
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())

